### ISSUE TITLE
OAuth signature does not match

### ISSUE THREAD

**Issue by bobsilon** [WP-API/OAuth1#107]
Hi there,
I've read issue https://github.com/WP-API/OAuth1/issues/34, but can't get answer.
What I actually do, in postman I POST to `http://localhost/wp-bobsilon/oauth1/request` with the below body as described in [documentation](http://oauth1.wp-api.org/docs/basics/Auth-Flow.html):

Key | Value
------|------
OAuth realm | Example
oauth_consumer_key | EzbGR0fpghOL
oauth_callback | client.example.com/cb
oauth_signature_method | HMAC-SHA1
oauth_timestamp | 1449585142
oauth_nonce | 793e554ac0
oauth_signature | ...

And The Result is `OAuth signature does not match`.
Am I doing something wrong?
What is `OAuth signature` and how to get one?

**Comment by rmccue** [comment]
The OAuth signature needs to be generated for each request. See [the guide](http://oauth1.wp-api.org/docs/basics/Signing.html) on how to do this. Postman has [a helper](https://www.getpostman.com/docs/helpers) to do this that you might be able to use :)
