### ISSUE TITLE
Return `user_id` of authenticated user with access token

### ISSUE THREAD

**Issue by beaulebens** [WP-API/OAuth1#110]
When requesting an access token at the end of the auth handshake, it's relatively common practice to include some sort of user identifier (in our case, probably just WP user id). Failing this, the WP-API probably needs to support some sort of "me" alias when requesting `/users/` so that you can determine "who am I". This is a really common thing to need to do using APIs like this. Example:

1. Ask user to authenticate against remote WP
2. Bounce through auth flow
3. Attempt to display "you are connected as this user"

In step 3, we don't know who a token belongs to because 1. there's no user information supplied back in the token, combined with 2. there's no (apparent) way to request "who does this token belong to" from WP-API.

**Comment by kosso** [comment]
We already have this. 

I use `/wp/v2/users/me?context=embed` to verify/identify the user after authorization.

**Comment by beaulebens** [comment]
Huh, you're right. Now that you point that out, I took a look in the code, and it looks like it's delivered along with a `302` redirect, which seems a little weird. I'm guessing my client library didn't handle that properly since it's not a `2xx`, will play around.

**Comment by beaulebens** [comment]
Weird - If I request `/users/me` I get a 401, complaining about `json_oauth1_signature_mismatch`. If I change it to request `/users/<id>`, and keep everything else exactly the same, it works fine.

**Comment by lewg** [comment]
@beaulebens Make sure your client library isn't following the 302 redirect that /users/me returns or it ends up making an unauthenticated call to the /users/XX endpoint, which throws the 401.

**Comment by joehoyle** [comment]
Closing this out as @lewg looks like to have the correct solution here.
