### ISSUE TITLE
oauth_callback for oob does not return verify code

### ISSUE THREAD

**Issue by mjacobsen4DFM** [WP-API/OAuth1#113]
Using org.glassfish.jersey.* Java libraries to make Oauth1 calls, using the OAuth1AuthorizationFlow manager.

The first call goes to https://my.com/oauth1/request containing the following params in the header:
oauth_nonce="cf6d8f35-3304-4fb6-94e3-194a2be9aaba"
oauth_signature="lao1T9hMAW5SuAOzYPQ2tyrMypU="
oauth_consumer_key="OT3iSHHi1xnb"
oauth_signature_method="HMAC-SHA1"
oauth_version="1.0"
oauth_timestamp="1450419223"
oauth_callback="oob"

Calling .start() on the flow manager returns the authorization URL of https://my.com/oauth1/authorize?oauth_token=Rafdr8RRK3dVL6Kvg5YfpoMT&oauth_callback=oob 

Following that link lands on an admin page, https://my.com/wp-login.php?action=oauth1_authorize&oauth_token=EXVvIJt2etJHe1p46s6xcnPi&oauth_callback=oob

On that page you are presented with a dialog saying, "Howdy admin,"the app" would like to connect to The Site." lets you "Authorize" or "Cancel" the request. 

Clicking on "Authorize" lands on https://my.com/wp-login.php?action=oauth1_authorize, a blank page with no verify code.

FYI: The WP site is a single site with self-generated SSL.

I have tried this against various instances and versions of WP-API and OAuth1; currently using WP-API Version 2.0-beta9 and Oauth Server 0.2.1
--Consumer was created using wp-admin/users/applications->add new
https://my.com/wp-admin/users.php?page=rest-oauth1-apps

**Comment by mjacobsen4DFM** [comment]
Also tried a cli approach...

Using wp-api/client-cli against consumer created via wp-cli
$ wp oauth1 add

ID: 4
Key: sDc51COH2mFu
Secret: LnUdIsyhPFnURminekRIAUfYV7nmP4iF3AVxkS5PRHPXxgOW

And trying to get authorization code using:
wp --require=client.php api oauth1 connect https://my.com/ --key=sDc51COH2mFu --secret=LnUdIsyhPFnURminekRIAUfYV7nmP4iF3AVxkS5PRHPXxgOW

Results in:
Error: Could not locate API; are you sure it's enabled?

I have verified that it is enabled. Also, going to https://my.com/oauth1/request returns:
No OAuth parameters supplied
Which seems pretty indicative of it running; also, the tokens received from the request above show a working API. So, I do not think the API not running is the problem.

**Comment by mjacobsen4DFM** [comment]
Trying to build everything by hand (removing/altering library methods)
So, this is a real, unaltered, call to request:
https://vccw.dev/oauth1/request?oauth_nonce=c359c04c-bf34-46ea-b94b-db174ffdf43b&oauth_signature=gpUYMt%2fKmg6wVbBZhcN8c44bkC4%3d&oauth_callback=oob&oauth_consumer_key=OT3iEXRL1xnb&oauth_signature_method=HMAC-SHA1&oauth_version=1.0&oauth_timestamp=1450451052

returns:
OAuth signature does not match

**Comment by mjacobsen4DFM** [comment]
I found the issue. The library I am using forces callback to "oob" (behind the scenes), which doesn't match the cli user. When the wp-admin/applications user is configured with an "oob" callback to match, it doesn't behave as I expected. Not sure if I misread, or I misunderstood, or it is misleading; but, I will research that for my own edification at a minimum. But, I am closing this issue.

**Comment by AleeRojas** [comment]
could you fix it?

**Comment by mjacobsen4DFM** [comment]
Yes, but all I can tell you is what I did in my closing statement. The library and the cli/ui didn't agree.
