### ISSUE TITLE
OAuth on shared hosting

### ISSUE THREAD

**Issue by dleeward** [WP-API/OAuth1#118]
Will OAuth be part of core in WP v4.5? If it is, will it work on shared hosting without access to the cli? If not, are there plans to update to be able to install on shared hosting?

**Comment by mnelson4** [comment]
FYI to my knowledge there are no plans (yet) to make oAuth part of core. Maybe someday, but no estimate has been given.
To my knowledge this plugin should work fine on shared hosting without access to the command line interface. You just create the applications using the wp dashboard -> users -> applications.

**Comment by dleeward** [comment]
> You just create the applications using the wp dashboard -> users -> applications.

Where is that?

**Comment by rmccue** [comment]
Install and activate the latest plugin, then there'll be a Applications page under the Users heading in the dashboard. :)

**Comment by dleeward** [comment]
Thanks

**Comment by joehoyle** [comment]
Closing, all looks good here.
