### ISSUE TITLE
Could not locate API; are you sure it's enabled?

### ISSUE THREAD

**Issue by zubaer-ahammed** [WP-API/OAuth1#119]
I am getting "Could not locate API; are you sure it's enabled?" when I try to link client to WordPress. I have installed all necessary plugins and dependencies are installed & activated including (WP-REST API, oAuth1 etc). When I try HEAD http://mywebsitelink it returns link with wp-json which indicates WP-API is working. Also, when I try wp oauth1 add, it works fine and generates key and secret. 
Any suggestion on how to fix this issue? Thanks in advance.

**Comment by kosso** [comment]
Which version of WP and WP-API are you on?

**Comment by zubaer-ahammed** [comment]
WordPress Version 4.4.1, WP-API Version 2.0-beta9 and OAuth 1.0a Server version 0.2.1

**Comment by kosso** [comment]
I'm working on : 

- WP 4.4.2-alpha  (I think you need to use the Beta nightlies, though I can't find the link in docs where I read that. It might not still be the case.)
- OAuth1.0a Version 0.2.1 
- WP-API Version 2.0-beta9 

What happens if you simply visit http://mywebsitelink/oauth1/request ? -  It should just say "No OAuth parameters supplied"

**Comment by zubaer-ahammed** [comment]
Yes, It does say "No OAuth parameters supplied" when I visit my stie: http://wordpressinsights.com/oauth1/request

**Comment by kosso** [comment]
If that's working, and you that your /wp-json is working, showing you the endpoints, then it could be your client causing the issue.  What client are you using? 

Try this test PHP client script I wrote a while ago. Naturally, run it on another domain as if it was a remote client. 

https://gist.github.com/kosso/71c957e30a40116e5f98

**Comment by zubaer-ahammed** [comment]
Thanks for the script. But when I run this script, it get's nothing in $request_token_string and not working for me.
```
$request_token_string = $auth->oauthRequest($oauth_config["uri_request"],'POST', null, null);
```

I am using Windows, Also, I tried it from my Ubuntu and CentOS server. But sitll it reruns error. 

Here's what I tried to do:

In the root of WordPress installation I generated 'key' and 'secret' with 
```
wp oauth1 add

```

Then, I went to the ~/client-cli directory and run this:

```
wp --require=client.php api oauth1 connect http://wordpressinsights.com/ --key=p2W10zx8HvH5 --secret=jsp4maM7witdYvFruVTayQBlLpXmDZoqXJHCz9cZgbf0bSqg
```

Can you please try this key to check if it's working in your client.

**Comment by bilalvirgo10** [comment]
The latest version of the OAuth plugin doesn't work with the Client CLI package.

**Comment by kadamwhite** [comment]
@zubaer-ahammed I'm closing this out since there hasn't been any discussion for a while, but if you're still having issues please re-open and we'll see what we can do!
