### ISSUE TITLE
Consider making this plugin a client as well as a server

### ISSUE THREAD

**Issue by jtsternberg** [WP-API/OAuth1#124]
To me, this would not be a huge stretch, and has [prior art](http://docs.elgg.org/wiki/OAuth). This would mean that 2 WP instances running this plugin would be able to talk to each other via the API.

We have already used our [wp-client plugin (which is the middle of rewrite to better conform to OAuth spec)](https://github.com/WebDevStudios/WDS-WP-REST-API-Connect-UI) on a couple projects, and it's clear that the need will not be going away. I'd be happy to collaborate on combining the two to allow this plugin to act as a client or server.

**Comment by jtsternberg** [comment]
(selfishly, I don't want to have to maintain our plugin separately and have to account for [changes to things like the signature methods](https://github.com/WP-API/OAuth1/pull/122), etc)

**Comment by kosso** [comment]
Maybe you're missing the point?

The clients are (once you learn how OAuth works, actually) easy. And libraries exist to cater for the 'standard'. 

Changes to OAuth1.0a are not going to happen. The people who defined it have left. Some not proudly.

The far easier to work with OAuth2.0 needs https by default. Not everyone has that yet.

**Comment by jtsternberg** [comment]
@kosso I understand all that, and am not missing the point. It sounds to me like you are missing my point, which is that it would make sense for this plugin to both act as the server as well as a client for connecting WordPress instances.

**Comment by kosso** [comment]
Sorry. But I still don't see why? 

Once running the server, surely you can create any client in any language you like? And give it access from anywhere?

Here's one in PHP I put together : https://gist.github.com/kosso/71c957e30a40116e5f98

Not saying what you suggest *couldn't* be done. I just just don't understand why anyone would want to. 

:)

**Comment by rmccue** [comment]
I'm :-1: on the idea, mainly because it increases the scope of the project unnecessarily. The focus of this plugin is on providing access to a site with OAuth, not to be the one-stop-shop for everything OAuth-related.

If we include an OAuth client, we also risk accidentally making ourselves incompatible with the OAuth specification, which is potentially the issue in #122. Basically though, everyone should be speaking the OAuth spec over the wire, and we need to fix it if it's broken.

**Comment by jtsternberg** [comment]
>  it increases the scope of the project unnecessarily

Makes sense.

> If we include an OAuth client, we also risk accidentally making ourselves incompatible with the OAuth specification

How is that risk any different as an OAuth server?
