### ISSUE TITLE
Callback URL is not calling

### ISSUE THREAD

**Issue by maksumon** [WP-API/OAuth1#135]
After successful login and authorize the page stuck at "Your verification token is ....." but not calling the Callback URL.

Would anyone please help me solving this issue?

**Comment by maksumon** [comment]
![simulator screen shot 11 apr 2016 11 27 13 pm](https://cloud.githubusercontent.com/assets/1089462/14432516/17401546-003d-11e6-905f-5a77f6e74900.png)

This is where it stuck but never redirect to Callback URL.

**Comment by websupporter** [comment]
You need to add the callback url via `oauth_callback` this worked for me:
`http://url-to-authorize.com/?oauth_callback=http...my-callback-url&oauth_token ....`

**Comment by maksumon** [comment]
I'm using iOS app and custom URL Scheme

**Comment by maksumon** [comment]
Fix after pulling the latest update via git. Previously tried just downloading the .zip file. In iOS doesn't to set callback URL manually, library does that.

Thanks for your answer for web app.
