### ISSUE TITLE
Mismatching OAuth Signatures

### ISSUE THREAD

**Issue by oneeyedjames** [WP-API/OAuth1#143]
I've been getting intermittent instances of `OAuth signature does not match`.

After tinkering, I found that any `+` in the signature gets converted to a space in WP_REST_OAuth1::parse_header(). The cause seems to be the use of `urldecode()`, as below. I tried changing it it to `rawurldecode()` and it worked flawlessly. Has anyone else experienced this?

```php
		$params = array();
		if ( preg_match_all( '/(oauth_[a-z_-]*)=(:?"([^"]*)"|([^,]*))/', $header, $matches ) ) {
			foreach ($matches[1] as $i => $h) {
				$params[$h] = urldecode( empty($matches[3][$i]) ? $matches[4][$i] : $matches[3][$i] );
			}
			if (isset($params['realm'])) {
				unset($params['realm']);
			}
		}
```

**Comment by oneeyedjames** [comment]
I've added a pull request changing `urldecode()` to `rawurldecode()`. https://github.com/WP-API/OAuth1/pull/144

**Comment by rmccue** [comment]
I believe the current behaviour is correct per the [OAuth specification](https://tools.ietf.org/html/rfc5849#section-3.4.1.3.1):

> While the encoding rules specified in this
> specification for the purpose of constructing the signature base
> string exclude the use of a "+" character (ASCII code 43) to
> represent an encoded space character (ASCII code 32), this practice
> is widely used in "application/x-www-form-urlencoded" encoded values,
> and MUST be properly decoded, as demonstrated by one of the "a3"
> parameter instances (the "a3" parameter is used twice in this
> request).

I could be wrong though, maybe I'm reading that incorrectly?

**Comment by oneeyedjames** [comment]
Good point. [Section 3.5.1](https://tools.ietf.org/html/rfc5849#section-3.5.1) does state that header parameter values should be percent-encoded as well, so I'll need to revisit my client code. If the header values are properly encoded, then both decoding functions should behave according to spec.

For the sake of consistency, though, would it still make sense to use `rawurlencode()`? The corresponding `rawurlencode()` actually encodes according to [RFC3986](https://tools.ietf.org/html/rfc3986#section-2.3), while `urlencode()` doesn't.

**Comment by rmccue** [comment]
We should be using `rawurlencode()` everywhere, but I don't think there's anything that actually does encoding? The decoding needs to be `urldecode()` though so we can accept `+`

**Comment by joehoyle** [comment]
I don't think there's anything to do here, closing
