### ISSUE TITLE
"OAuth signature does not match" when using "ddo/oauth-1.0a"

### ISSUE THREAD

**Issue by sftsk** [WP-API/OAuth1#146]
Hello,

I have spent hour debugging this but finally found a solution.
I am not sure if I am doing everything right which is why I would like to share what I came up with.

After digging through the code I found out that your plugin is creating the hash using token + secret as the key whereas "ddo/oauth-1.0a" is only using the secret without the token.

I have added the following after line `686` of `class-wp-rest-oauth1.php ` so that it looks like following:

```
$key = implode( '&', $key_parts );
// hot fix by sftsk
$cut_pos = strpos($key, '&');
$key = substr($key, 0, $cut_pos + 1);
```

I am really not sure if this is good practice, could you please elaborate if this indeed is an issue with your plugin or if  "ddo/oauth-1.0a" is doing something wrong.

Thank you for the great work,
best,

Lukas

p.s.: have added a pull request now: #147

**Comment by rmccue** [comment]
This is definitely incompatible behaviour. The spec specifically says [in §3.4.2](https://tools.ietf.org/html/rfc5849#section-3.4.2):
>     key     is set to the concatenated values of:
>
>             1.  The client shared-secret, after being encoded
>                 (Section 3.6).
>
>             2.  An "&" character (ASCII code 38), which MUST be included
>                 even when either secret is empty.
>
>             3.  The token shared-secret, after being encoded
>                 (Section 3.6).

I see you've filed this upstream with the library, so closing this out and the pull request as well; thanks for investigating!
