### ISSUE TITLE
Can the oauth_token / oauth_token_secret expire?

### ISSUE THREAD

**Issue by scofennell** [WP-API/OAuth1#150]
Hi!

I'm unclear from the docs as to whether I should be concerned about tokens expiring.  Assume for the sake of argument that in this case I'm hard-coding the oauth_token / oauth_token_secret into a privately hosted plugin, rather than storing them in a cookie.

I'm at the edge of my skillset here, my apologies if this is a stupid question.

**Comment by kosso** [comment]
The tokens don't automatically expire.  They need to be manually revoked by the user it was created for. See the list of tokens in the user's Profile page in wp-admin : /wp-admin/profile.php

**Comment by scofennell** [comment]
Excellent response, thank you Kosso.
