### ISSUE TITLE
No Oauth parameters supplied

### ISSUE THREAD

**Issue by Critter** [WP-API/OAuth1#157]
When I hit domain.com/blog/oauth/request with a simple GET, I get 'No Oauth parameters supplied'

I downloaded: https://github.com/WP-API/example-client and fired it up. Discovery worked fine, I put in my credentials and still receive the same error:

![error image](http://b-cr.it/2bzyh6v)

any suggestions would be greatly appreciated.

**Comment by kosso** [comment]
Hi there Crit! 

You can check out a test script I did a while ago which should still work. 

https://gist.github.com/kosso/71c957e30a40116e5f98

To get authorization, you need to first do a signed `POST` to `oauth.request` to get the parameters to use for the GET request to the `oauth/authorize`url. (See L288) 

That will present the user with a Wordpress login on domain.com. 

After returning from authorization (to your supplied `oauth_callback` url) you'll then have all the info required to make a `POST` to `oauth/access` and get an access token and secret. 


hth ;)

**Comment by Critter** [comment]
oi mate. small world, eh?  This thing is absolutely driving me batty. I can get even the discovery thing to work locally, but when I attempt to use it on the development server... it's kicking my ass.

I used your script.. filling in all the bits, and such, but when I'm presented to 'login to authorize' I still get the same.. well it's cause by the same. I get this error:

![error](https://ctzdrops.s3.amazonaws.com/hJnF2jZnpt.png)

and the url reads as such: `/wp-login.php?action=oauth1_authorize&No%20OAuth%20parameters%20supplied&oauth_callback=...`

searching on `no auth parameters supplied` just leads me in a bloody circle to where I've already been.. \*sigh\*

**Comment by kosso** [comment]
Small word indeed. But one with huge possibilities! :) 

Do you have your httpd.conf/sites-available or .htaccess all set up?

**Comment by kosso** [comment]
In my script, I have a 'logIt' function here and there that you can tail the server errors/logs with and see if you're getting the appropriate OAuth headers.

**Comment by Critter** [comment]
Man - o - man. I literally /just/ stumbled on this [post](http://ravennainteractive.com/2016/08/getting-wordpress-rest-api-running-basic-auth-application-passwords/). I modified the .htaccess file to have this `RewriteRule ^index\.php$ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]` and now everything works as it should

Thanks for your help mate.  I think I am going to step away from the computer for the rest of the day. and drink.

**Comment by kosso** [comment]
Wise move. Heh. Usually the way. 

Glad you got it sorted out ;)
