### ISSUE TITLE
HackerOne abandoned?

### ISSUE THREAD

**Issue by thiago-negri** [WP-API/OAuth1#158]
I submitted a possible security breach on this project on HackerOne on Sep 5th 2015 (over 1 year ago).

And received absolutely no response on it.

Does anyone care?

**Comment by kosso** [comment]
Do you have a link? 
Do you let anyone know?

**Comment by kadamwhite** [comment]
As a maintainer of the REST API project this was not something I was ever personally aware of. I will check with the other maintainers at our meeting this week to see if it made it to any of us.

**Comment by thiago-negri** [comment]
@kosso I'm not familiar with HackerOne, but I guess it notifies project maintainers. As security breaches should be disclosed in a responsible manner, I wouldn't open a public issue for this. In case you have access to HackerOne for this project, that's the report link: https://hackerone.com/reports/87606

@kadamwhite Thanks, I bet something felt through the cracks. It may even be that my HackerOne report is malformed or something. Please keep me posted.

**Comment by joehoyle** [comment]
We added a bunch more people to the HackerOne account to make sure we get eyes on all submitted issues. First and foremost: we certainly do care! And thanks a huge amount of reporting it. I have read through it and we'll be working on picking it apart to make sure we fully understand and patch the issue.

In regards to this ticket directly, no, hackerone is not abandoned, and we're now in a much better position with an extra 4 people being added to the hackerone account. Thanks so much for following up!
