### ISSUE TITLE
Switching users during authentication problem

### ISSUE THREAD

**Issue by nursahketene** [WP-API/OAuth1#164]
I get a `missing parameter oauth_token` when trying to login but in the middle of the authentication I switch users. So here is the flow.

Application makes a request to this url: `http://example.com/wp/wp-login.php?action=oauth1_authorize&oauth_token=oThslEeBciYF660pyTTx2QgH` 

![screen shot 2016-10-10 at 11 59 49](https://cloud.githubusercontent.com/assets/143079/19231147/14a0f32c-8ee1-11e6-96e9-c53b057041a3.png)

I click switch user and I get the following url `http://example.com/wp/wp-login.php?redirect_to=http%3A%2F%2Fexample.com%2Fwp%2Fwp-login.php%3Faction%3Doauth1_authorize&reauth=1`

I enter my credentials and click 'Login' and I will get the the error message `missing parameter oauth_token` with the following url:
`http://example.com/wp/wp-login.php?action=oauth1_authorize`

Notice no more oauth_token available in the url.

**Comment by rmccue** [comment]
Thanks for the bug report! Filed a PR to fix it: #175.
