### ISSUE TITLE
TokenCredentials url

### ISSUE THREAD

**Issue by sigaev-pro** [WP-API/OAuth1#172]
Hi!

I'm trying to build Client for  [Laravel Sociolite](https://github.com/laravel/socialite) as example I'm using [Twitter Provider](http://socialiteproviders.github.io/providers/twitter/) as of Twitter also using OAuth1. For the first look, it is all right, but I dont understen where find URL to get TokenCredentials.

**Comment by rmccue** [comment]
Per [the documentation](https://oauth1.wp-api.org/):

> The endpoints for the OAuth process are available in the REST API index: check for `$.authentication.oauth1` in the index data.
>
> * The temporary credentials (request token) endpoint is `$.authentication.oauth1.request` (typically `/oauth1/request`)
> * The authorization endpoint is `$.authentication.oauth1.authorize` (typically `/oauth1/authorize`)
> * The token exchange (access token) endpoint is `$.authentication.oauth1.access` (typically `/oauth1/access`)
