### ISSUE TITLE
Should `wp_scope` be asked by the client?

### ISSUE THREAD

**Issue by andreilupu** [WP-API/OAuth1#183]
Hello everybody, I want to start by congratulating you for this very useful plugin.

I have a trivial question about the fact that the server application doesn't manage the API's scope.
Isn't dangerous to let the client declare the scope? Even further, should the default scope be as permissive as "*"?

Personally, I would do it like GitHub does in the application panel, put a checkbox for each scope type and by default the scope should be just "read" or "user.read."

I'm willing to put my hands at work in a PR if my idea makes sense in some way for you.

**Comment by rmccue** [comment]
Scopes are actually not implemented at all yet, so there's no real danger. They're a potential enhancement, however there hasn't been a huge demand for it, and it's complex technical work, so it remains to be seen whether it's implemented. :)

Happy to accept PRs if you do want to implement them of course!
