### ISSUE TITLE
Oauth Signature does not match when signing a request programatically.

### ISSUE THREAD

**Issue by scbritton** [WP-API/OAuth1#184]
I'm running into an issue with programming a hashed signature that works with the system.  

Here is what I know:

- The Oauth server has been installed and is working properly
- I have successfully generated a shared token/secret through the 3-leg authorization process using Postman.
- I am able to submit a signed request and get a valid response from my install including JSON data in the request body, using postman, 

So I know the system works.

Now, because I'm trying to automate a client to communicate with my server, I need to automatically timestamp and sign the requests, so I am generating a request using PHP and sending it with CURL.

Here's the code (and yeah, it's likely quite messy as I'm still in the beating-head-on-desk phase of development here)...

```
// These two values identify the application (on dev.StevenBritton.net)

	$consumerKey = "consumer-key";
	$consumerSecret ="consumer-secret";

	// These two values are the client's individual long-term credentials.

	$oToken = "client-token"
	$oSecret = "client-secret";

	// Nonce to assign to the signature

        //add_filter( 'nonce_life', function() { return 300;} );  // I had this because I wanted short-lived nonces.
	$timeStamp = time();
	$nonce = wp_create_nonce($timeStamp); // Not really sure what I should pass to this here...
        //remove_filter( 'nonce_life',function() { return 300;});

       // urlencode everything.  I'll clean this up a bit later...
       $base_method = urlencode('POST');
       $base_url = urlencode('http://dev.stevenbritton.net/wp-json/custom/path/that/works');
       $oauthConsumerKey = urlencode('oauth_consumer_key='.$consumerKey);
       $oauthNonce = urlencode('oauth_nonce='.$nonce);
       $oauthSignatureMethod = urlencode('oauth_signature_method=HMAC-SHA1');
       $oauthTimestamp = urlencode('oauth_timestamp='.$timeStamp);
       $oauthToken = urlencode('oauth_token='.$oToken);
       
       $sigBase = $base_method . '&' . $base_url . '&' . $oauthConsumerKey . '&'. $oauthNonce . '&'.$oauthSignatureMethod.'&'.$oauthTimestamp.'&'.$oauthToken;
       $keyBase = $consumerSecret . '&' . $oSecret;
       
// Here's the line that generates the signature...

       $signature = hash_hmac('sha1',$sigBase,$keyBase);

//  Build the CURL request:
$url = "http://dev.stevenbritton.net/wp-json/stevenBritton/licenseMe/v1/single?" . urlencode($auth_string);

$curl = curl_init();


	curl_setopt_array($curl, array(
	CURLOPT_URL => $url,
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_ENCODING => "",
	CURLOPT_MAXREDIRS => 10,
	CURLOPT_TIMEOUT => 30,
	CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
	CURLOPT_CUSTOMREQUEST => "POST",
	CURLOPT_HTTPHEADER => array(
	  "authorization: OAuth oauth_consumer_key=\"" . $consumerKey . "\",oauth_token=\"" . $oToken . "\",oauth_signature_method=\"HMAC-SHA1\",oauth_timestamp=\"" . $timeStamp . "\",oauth_nonce=\"" . $nonce . "\",oauth_signature=\"" . $signature . "\"",
	  "cache-control: no-cache",
	  "content-type: application/json"
	),
));
       curl_setopt($curl, CURLOPT_POSTFIELDS, $json);

       $response = curl_exec($curl); // <-- craps out.  Every time I get "signature does not match"
       $err = curl_error($curl);

       curl_close($curl);

       if ($err) {
         echo "cURL Error #:" . $err;
       } else {
         echo $response;
       }


```

So, here's the question:

What am I doing differently than the OAuth machine that is causing my signature to mismatch the verification, when Postman does it correctly?

**Comment by kosso** [comment]
Have you tried sorting your `oauth_..` authorization headers in alphabetical order first?

**Comment by scbritton** [comment]
Yes.  Unless I'm missing something, they are indeed in alphabetical order in sigBase

Get Outlook for iOS




On Sat, Nov 26, 2016 at 4:57 AM -0700, "Kosso" <notifications@github.com> wrote:












Have you tried sorting your oauth_.. authorization headers in alphabetical order first?

**Comment by scbritton** [comment]
Using your test script and some narrowing down, I've managed to narrow the problem down to the attachment of the JSON data - it works without JSON, but when the JSON is added (in your script it's the CURL Setopt line after the $header[] array is created and the content-type, oauth header, etc is added to it.  Commenting out the setopt line that deals with HTTPHEADER(working from memory here) makes it work - but it's useless because I need JSON attached. 



On Sat, Nov 26, 2016 at 4:57 AM -0700, "Kosso" <notifications@github.com> wrote:












Have you tried sorting your oauth_.. authorization headers in alphabetical order first?

**Comment by kosso** [comment]
See around line 450 where I had to treat JSON encoded data differently. Maybe that's your problem.

My OAuth methods/tests are not the best! :) But I got it all to work eventually, Just.  With some hair still left on my head.

**Comment by scbritton** [comment]
In your test app, it's line 485 that, commenting out, makes the OAuth work, but the JSON is undetected in that event.  So I don't know what's going on here...

**Comment by rmccue** [comment]
We strongly, strongly recommend using an existing library for OAuth signature generation. It's very easy to make mistakes when writing this yourself, as the process is pretty complicated and has to be exactly correct. The League of Extraordinary Packages has a [great library](https://github.com/thephpleague/oauth1-client) for doing this.

If you really do want to write this yourself (and again, I strongly discourage doing so): your signature base is incorrectly prepared. It has three parts: method, URL, and parameters; these are separated by `&`. The parameters are also separated by `&`, but the whole parameter section needs to be URL-encoded before put into the base string.

Specifically:
```php
$sigBase = $base_method . '&' . $base_url . '&' . $oauthConsumerKey . '&'. $oauthNonce . '&'.$oauthSignatureMethod.'&'.$oauthTimestamp.'&'.$oauthToken;
```

Should be:
```php
$sigBase = $base_method . '&' . $base_url . '&' . urlencode($oauthConsumerKey . '&'. $oauthNonce . '&'.$oauthSignatureMethod.'&'.$oauthTimestamp.'&'.$oauthToken);
```

There are other pieces here which will break: in particular, the OAuth nonce needs to be a real nonce (number used once), which WordPress nonces are not. Once again, you're much better off using a library, which can generate these in a secure way and handle storage of the nonces.
