### ISSUE TITLE
Clarification on use of OAuth 1 vs 2

### ISSUE THREAD

**Issue by BRMatt** [WP-API/OAuth1#2]
I had a look over the spec but couldn't see any explicit discussion about why version 1 of the protocol was chosen over v2. The closest I saw to an explanation was this line:

> The API must work on any site. The API must only use features available to the majority of sites in order to provide a useful utility.

Which I presume is hinting that you can't rely on all sites having SSL to protect v2's secret credentials?

**Comment by seanfisher** [comment]
+1 as well for OAuth 2 support.

**Comment by joehoyle** [comment]
OAuth2 is not currently in the works by the REST API team due to the HTTPS requirement, we are trying to focus on the solutions that work for (virtually) all WordPress sites, however I do encourage any contributors to work on an oauth2 plugin :)
