### ISSUE TITLE
PHP 8.0 warning thrown by normalize_parameters

### ISSUE THREAD

**Issue by szaqal83** [WP-API/OAuth1#223]
After switching from PHP 7.4 to 8.0 a warning is thrown:

[16-Dec-2020 10:43:09 UTC] PHP Warning:  WP_REST_OAuth1::normalize_parameters(): Argument #2 ($value) must be passed by reference, value given in /.../wp-content/plugins/rest-api-oauth1/lib/class-wp-rest-oauth1.php on line 672

**Comment by szaqal83** [comment]
Proper callback should look like this:

`protected function normalize_parameters( &$value, $key ) {
		// $key = self::urlencode_rfc3986( rawurldecode( $key ) );
		$value = self::urlencode_rfc3986( rawurldecode( $value ) );
	}`

**Comment by scottfennell-toptal** [comment]
Are you sure you have the params in the correct order?  Previously, it was $key first, $value second:

https://github.com/WP-API/OAuth1/blob/master/lib/class-wp-rest-oauth1.php#L754

**Comment by szaqal83** [comment]
Params order is fine, normalize_parameters is called here:
/.../wp-content/plugins/rest-api-oauth1/lib/class-wp-rest-oauth1.php on line 672
`// normalize parameter key/values
		array_walk_recursive( $params, array( $this, 'normalize_parameters' ) );`
according to PHP docs https://www.php.net/manual/en/function.array-walk-recursive.php
"Typically, callback takes on two parameters. The array parameter's value being the first, and the key/index second."
so declaration of normalize_parameters function in
/.../wp-content/plugins/rest-api-oauth1/lib/class-wp-rest-oauth1.php on line 754
has wrong params order, it is:
`protected function normalize_parameters( &$key, &$value ) {
...
}`
it should:
`protected function normalize_parameters( &$value, $key ) {
		// $key = self::urlencode_rfc3986( rawurldecode( $key ) );
		$value = self::urlencode_rfc3986( rawurldecode( $value ) );
	}`

**Comment by scottfennell-toptal** [comment]
But if you change the order of the params in the function definition, don't you need to also change their order when calling the function?

Maybe in this case you don't, because of the way array_walk_recursive works(), but I can't quite make out why.  The code is a bit overly clever :D

**Comment by szaqal83** [comment]
No you don't need to change order of params passed because there is only one param ($params is an array).

**Comment by szaqal83** [comment]
I think this is the preferred way now [https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/](url).

**Comment by szaqal83** [comment]
Will there be an update here: [https://wordpress.org/support/plugin/rest-api-oauth1/](https://wordpress.org/support/plugin/rest-api-oauth1/) ?
