### ISSUE TITLE
PHP 8.3 compatibility - Deprecated: Calling get_class() without arguments is deprecated

### ISSUE THREAD

**Issue by szaqal83** [WP-API/OAuth1#233]
Using version 0.4.1 with PHP 8.3 causes deprecation warning: **Deprecated: Calling get_class() without arguments is deprecated**. Easy fix is to switch from `get_class()` to `static::class`. The `self::class` magic constant is available in PHP 5.4 and later.

Will there be any update here: [https://wordpress.org/plugins/rest-api-oauth1/](https://wordpress.org/plugins/rest-api-oauth1/) ? Published version is 0.3.0, most recent version is 0.4.1.

**Comment by spacedmonkey** [comment]
@szaqal83 I have put together a PR at #240. Do you mind taking a look / reviewing?

**Comment by szaqal83** [comment]
I'll check in few moments.

**Comment by szaqal83** [comment]
I confirm it fixes deprecation warning: **Deprecated: Calling get_class() without arguments is deprecated.**
