### ISSUE TITLE
Authenticating without WP CLI

### ISSUE THREAD

**Issue by paulruescher** [WP-API/OAuth1#25]
Could anyone shed some light on authenticating without actually using WP CLI? I've created an API client and have a key/secret, but am unsure of what the next steps are.

**Comment by rmccue** [comment]
Basically, in your API client, you need to use the OAuth 1.0a authentication process to talk to the site. This is a bit obtuse, so it's best to use an existing library for that.

We need better documentation on this.

**Comment by rmccue** [comment]
We now have [better docs](http://oauth1.wp-api.org/) as well as admin UI for this. Sorry for the delay!
