### ISSUE TITLE
OAuth Server accept signature

### ISSUE THREAD

**Issue by cynex** [WP-API/OAuth1#27]
Ive been trying to get this to work with WP-API on my Wordpress install, using the chome extension postman to test the oauth api. For some reason, the signatures do not match. I have used the appropriate consumer key / secret and generated the signature just fine on the postman client, but when i test that against the oauth response, they never match up. in the file "class-wp-json-authentication-oauth1.php" on line 560 :

$signature = base64_encode( hash_hmac( $hash_algorithm, $string_to_sign, $key, true ) );

		if ( $signature !== $consumer_signature ) {
			return new WP_Error( 'json_oauth1_signature_mismatch', __( 'OAuth signature does not match'), array( 'status' => 401 ) );
		}

I have echoed the $signature along with the error message, and then tested that signature using postman, and indeed it worked. So, can someone explain to me how we can get this to function correctly ? (postman is just my intermediary step -- Im actually indending to use guzzle + subscribe)

**Comment by tripflex** [comment]
Make sure that your signing correctly, especially if using POSTMAN:
http://oauth1.wp-api.org/docs/basics/Signing.html

If you're using POSTMAN you can set it to OAuth 1.0 under Authorization and then select the options below (don't enable "add params to header")

 - Add empty params to signature
 - Encode OAuth signature
 - Save helper data to request

Mine did not work until I specifically enabled those options, as enabling `add params to header` will actually change the signature ;-)

**Comment by joehoyle** [comment]
Closing this out now, all looks ok here.
