### ISSUE TITLE
URL callback validator is overly strict for non-web clients

### ISSUE THREAD

**Issue by trevordevore** [WP-API/OAuth1#28]
I'm trying to connect a desktop client to a WordPress blog using this library. After making some changes to the check_oauth_signature function I was able to get the URL to open in a web browser so that the user could log in and grant access to my application. 

When attempting to redirect the browser reported the error "The callback URL is invalid". In the handle_callback_redirect function the following validation is applied to $callback:

    $callback = wp_http_validate_url( $callback );

This validation is problematic for desktop applications. A desktop application has three approaches to using OAuth:

1. Designate a custom URL protocol that the browser passes off to the desktop application (e.g. myapp://)
1. Listen on a port of the localhost (e.g. 127.0.0.0:9999)
1. Perform the whole operation within a browser hosted in the desktop application and intercept the callback URL.

(3) never made sense to me as the user has no way of ensuring that you are indeed sending them to the right website.

I've used (1) and (2) in the past. I use (1) with the OAuth implementations for Dropbox and Evernote.

The issue here is that the OAuth1 code thinks that 127.0.0.1:9999 is an invalid URL. wp_http_validate_url() seems overly strict for the purposes of an OAuth callback URL. I know some services with only allow "http" prefixed URLs or they make you register the callback URL with the service.

**Comment by yoshito-maeoka** [comment]
+1 too.
For iOS app would be ideal, if we can define a custome protocol. It would be great if we could define by getting consumer key like:
```
$ wp oauth1 add --custom-protocol=myapp://
```
then save this protocol, somewhere in wordpress system or somewhere related with the plugin.

**Comment by seanfisher** [comment]
+1

**Comment by kosso** [comment]
We should be able to set `oob` for an "Out Of Band" callback. 

See oauth_callback in section 6.1.1

http://oauth.net/core/1.0a/

(btw: In some native apps I've done, when a provider doesn't support this, I use a fake url that my app knows is wrong, but expects. And as long as the provider doesn't verify that http://my.fake.url/for_my_app doesn't exist, I look for it in the error response and get the token fragments/params that way.)

**Comment by itsananderson** [comment]
I like the way GitHub handles this. They register the redirect URL when you register the app. Then they validate that any provided callback URL matches the host and port, and is a subdirectory of the registered redirect URL.

https://developer.github.com/v3/oauth/#redirect-urls

**Comment by shankiesan** [comment]
+1 for a solution here. I'm building a React.js app that consumes data from the API. This issue shouldn't cause any big problems in production, but is a hassle for development as a URL such as http://localhost:9090/callback fails. 

There's a workaround – add an entry into your host file, such as `127.0.0.1 local.dev`, but it's not particularly elegant.

How do the developers feel about the API having its own URL validator – such as @itsananderson 's suggestion to emulate GitHub's validator (probably with the addition of an OOB option)?

**Comment by rmccue** [comment]
Sorry for the lack of movement here! This is definitely a problem.

We definitely need a custom validator, and in addition, the ability to store the callback URL for a client so we can match against it. As for the actual validation, we need to make sure the URL scheme, authorization/userinfo, host, port, and path all match. Subdirectories of the registered URL should _not_ be supported right now, as they can open up a lot of potential issues.

FWIW, `oob` is already supported, and is the method that the CLI client uses to authenticate. I just tested locally, and it works there; if you can't get that to work, please file an issue. (I'm aiming to be more active on this repo, so hopefully we won't have to wait a year to get an issue resolved again. :) )

**Comment by kosso** [comment]
:+1:

**Comment by younes0** [comment]
thanks @shankiesan

**Comment by rmccue** [comment]
Fixed in #98; please try the latest master out and let me know how it goes, but it should fix all the issues here, including custom protocols. :)
