### ISSUE TITLE
WP_JSON_Authentication::add_consumer does not set title or description

### ISSUE THREAD

**Issue by bobbingwide** [WP-API/OAuth1#41]
When creating a consumer on the server it should be possible to give it a title and a description.
```
wp oauth1 add --name="title" --description="what you want to say about it"
```

This code, in WP_JSON_Authentication::add_consumer nearly works.
```
		$data = array();
		$data['post_title'] = $params['name'];
		$data['post_content'] = $params['description'];
		unset( $data['post_title'], $data['post_content'] );
		$data['post_type'] = 'json_consumer';
		$ID = wp_insert_post( $data );
```
But the unset() prevents the title and content from being set. 
If you comment out the unset(), the title will be displayed on the Authorize dialog.

Note: json_consumer is currently defined to be invisible to admin users on the dashboard. 
If you want to make it visible then you can hook into 'registered_post_type' to dynamically change the settings. Note that the posts are created with a status of 'draft'. If you want to see the actual values for the key, secret and type post meta data then you need to add 'custom-fields' post type support.

**Comment by rmccue** [comment]
Confirmed this issue, not sure why the unset was there. Will be fixed by #55.
