### ISSUE TITLE
Request: A simple cUrl or PHP example of using the access tokens to make an authenticated request

### ISSUE THREAD

**Issue by kosso** [WP-API/OAuth1#43]
Hi,
Great to see OAuth and the WP-API coming together! 

I've finally managed to get the OAuth server and everything else up and running, created a consumer and then obtained an access_token and access_token_secret for myself for the app (via PHP running on another domain see : https://github.com/kosso/OAuth1/blob/master/php_test/wp_oauth_test_auth_flow.php ) 

So, now I want to use the access token and secret to make an authenticated request to the WP-API JSON. eg: The most obvious first request after getting the access tokens would be to `/wp-json/users/me`  to provide the information about the logged in user back to a client app. 

Am I right in saying that `/wp-json/users/me` will now detect OAuth Authorization headers? 

My attempts so far have always resulted in the `json_not_logged_in` error. 

A simple cUrl or PHP (or JS) example would be great if anyone has one. 
Thanks.

**Comment by DatasoftSolutionsNet** [comment]
Thank you!
This is much needed!
