### ISSUE TITLE
App requests to /wp-json/users/me are failing.

### ISSUE THREAD

**Issue by kosso** [WP-API/OAuth1#45]
Please refer to this comment on WP-API : https://github.com/WP-API/WP-API/pull/493#issuecomment-62544383

I have successfully built and tested a [PHP OAuth client](https://github.com/kosso/OAuth1/blob/master/php_test/wp_oauth_test_auth_flow.php) to go through the authentication flow and then GET /wp-json/users/me  to verify the user.  This all works fine. (Note this only works when PHP cUrl CURLOPT_FOLLOWLOCATION is false - the default.) 

But when I try a native mobile app (in this case iOS built using Appcelerator Titanium), I can go through the authentication flow fine, then collect an access_ token/secret pair, but the final /wp-json/users/me GET request signature never matches. 

Lots of debugging and logging has shown that the client is being sent on a 2nd GET request to `/wp-json/users/<ID>` with the same parameters detected in `get_parameters()` from the original request. Therefore, the signatures don't match, as the REQUEST_URI is now different for the base string creation.  

Removing `$response->set_status( 302 );` from `class-wp-json-users.php` in WP-API seems to fix this.

**Comment by gregoirepuget** [comment]
Hi,

same for me with my own Aouth.

here is the return body
{"code":"json_user_cannot_list","message":"Sorry, you are not allowed to view this user."}

**Comment by kosso** [comment]
Closing this. 
I altered my client app to deal with the 302 redirection status.

**Comment by rmccue** [comment]
If you need to work around this, you can also try adding `?_envelope` to get it back in a wrapper object. See also [the FAQ on this](http://v2.wp-api.org/guide/problems/).

**Comment by kosso** [comment]
Ahah! That works too. thx! 

`/wp-json/wp/v2/users/me?_envelope=1&context=embed` did the trick.
