### ISSUE TITLE
oauth1 is not a registered wp command

### ISSUE THREAD

**Issue by jeffstahlin** [WP-API/OAuth1#48]
I am getting an error when attempting to create a consumer in the CLI. The wp command works fine, so I know that WP-CLI is correctly installed, however when I try to run the `wp oauth1 add` command I get the following error:

    Error: 'oauth1' is not a registered wp command. See 'wp help'

I have the WP-API and OAuth1 plugins installed in my Wordpress installation and I am running the command from within the Wordpress directory. 

Any help with this would be much appreciated.

**Comment by duncanjbrown** [comment]
Did you run `wp plugin activate OAuth1`?

**Comment by rmccue** [comment]
Please make sure the plugin is activated. If it is, and it's still not working, please reopen this ticket.
