### ISSUE TITLE
How to Revoke an Access Token ?

### ISSUE THREAD

**Issue by jon301** [WP-API/OAuth1#50]
Hi !

I've managed to get an access token, now I wondered if it is now possible to revoke it.
Does it have an expiration date or is it permanent until revocation ?

I see in the mysql database that all keys (request/access) are stored in the WP_OPTIONS table, but I hope there is another way to revoke an access key than suppressing them manually in database ?

Thank you for your help !

Jon

**Comment by rmccue** [comment]
Not currently possible via UI, but we need to add it as part of #55. Thanks for filing this!

**Comment by kosso** [comment]
I was wondering this too, until I found all the 'access' and 'request' entires in wp_options. 

There needs to be something expiring and removing these entries on a regular basis, surely?

**Comment by rmccue** [comment]
This is now possible; head to your profile page and hit the "revoke" button. :)
