### ISSUE TITLE
Cannot create consumer

### ISSUE THREAD

**Issue by zanematthew** [WP-API/OAuth1#53]
I've followed the [docs](http://wp-api.org/guides/authentication.html#basic-authentication), which appear to have some parsing issues, it looks like someone add an extra back tick when adding the commands to create the consumer.

Currently when I run: `$ wp oauth1 add` I see the following:

```
$ wp oauth1 add
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

Please note that my entire install is based on your [REST API Install](http://wp-api.org/#rest-api_installation) guide. Meaning, I have vanilla Vagrant, VirutalBox, and Chassis, set-up, and yes the plugins are activated.

So I'm at a loss as to why, the simple command `wp oauth1 add` isn't working.

**Comment by zanematthew** [comment]
Obviously I ran that command `wp core download`, which blew up my web root folder. Something should probably be mentioned about that :D

**Comment by zanematthew** [comment]
After some trail and error, I just moved this over to my "basic" local wp install, (http://wp.dev/) which is a base MAMP Pro set-up.

I receive the following:

```
$ wp oauth1 add
PHP Notice:  Undefined index: HTTP_HOST in phar:///usr/local/bin/wp/php/wp-cli.php(23) : eval()'d code on line 19
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:5
PHP   4. eval() phar:///usr/local/bin/wp/php/wp-cli.php:23
```

**Comment by rmccue** [comment]
With #55 and #98, you should now be able to do this entirely through the admin instead. Sorry for the wait on this.

**Comment by zanematthew** [comment]
Thanks.
