### ISSUE TITLE
adding consumer without cli

### ISSUE THREAD

**Issue by miran-tyran** [WP-API/OAuth1#54]
My hosting doesn't allow remote access, so I am unable to add a new customer. Is it possible to add a new consumer without wp-cli? Is it possible by adding some files to plugin directory? Is any admin UI for OAuth plugin planned?

**Comment by kosso** [comment]
After installing the plugin I *think*you should be able to do it in the wp-admin.  Can you see 'API Clients' on the left menu? 

/wp-admin/edit.php?post_type=json_consumer

**Comment by miran-tyran** [comment]
No, I don't - after using the URL you provided, I see the empty table, if I try to add one I get message "Invalid content type". Using latest WordPress 4.1.1, plugin installed by zipping the git clone and uploading a zip.

**Comment by kosso** [comment]
hmmm... it might be that the very first consumer needs to be added another way. It was a while ago that I set my test server up first time. 

I'm afraid that's all I know. Hopefully one of the authors might be able to help when they see this issue. ;)

**Comment by miran-tyran** [comment]
Sure, thanks for quick response anyway. I have limited connection now so can't download all necessary stuff to test locally. Maybe somebody will comment yet.

**Comment by rmccue** [comment]
Thanks for filing this. Work in progress on #55.
