### ISSUE TITLE
When can we use this? 

### ISSUE THREAD

**Issue by kosso** [WP-API/OAuth1#56]
Hi

Is there any indication yet as to when this functionality in the plug will find its way into WP-JSON (or core)? 

I have a working development app set up at the moment which all works fine for authenticating and posting (kinda). I'd like to get a couple of people I know to test it out, but I've been wondering whether I should wait for this plugin to get rolled-in (as I understood it) rather than ask them to install something temporary. 

Thanks.

**Comment by samwilson** [comment]
+1 Good question.

**Comment by romuloctba** [comment]
+20

**Comment by rmccue** [comment]
The plan is for this to get integrated into WP core when it's ready, which hopefully will be around the same time the endpoints do. Right now, as you might be able to see from the issues, there's various things we need to sort out first before we even release this properly.
