### ISSUE TITLE
$base_require_uri assumes HTTP - signature does not match over HTTPS

### ISSUE THREAD

**Issue by AlexC** [WP-API/OAuth1#60]
The following code will force HTTP to be used when constructing the $base_require_uri variable, meaning that the OAuth signature will not match if you're accessing WP-API w/ OAuth1 over HTTPS.

lib/class-wp-json-authentication-oauth1.php:554

```php
$base_request_uri = rawurlencode( get_home_url( null, parse_url( $_SERVER['REQUEST_URI'], PHP_URL_PATH ) ), 'http' );
```

The last argument to get_home_url should be removed, so that it is auto-detected.

**Comment by joehoyle** [comment]
This is merged and fixed, thanks!
