### ISSUE TITLE
Add Git Tags

### ISSUE THREAD

**Issue by franz-josef-kaiser** [WP-API/OAuth1#66]
This repo needs tags. Else no stable and reliable composer install will be possible.

**Comment by rmccue** [comment]
We'll tag it when it's ready for release :)

**Comment by franz-josef-kaiser** [comment]
@rmccue No tags? What happened?

**Comment by rmccue** [comment]
@franz-josef-kaiser Right now, it's not ready for release. As soon as it is, I'll tag it here, and it'll go up on the plugin repo.

**Comment by franz-josef-kaiser** [comment]
Why don't you just leave this open for later and/or simply add a tag like `0.1.0-alpha`?

**Comment by rmccue** [comment]
> Why don't you just leave this open for later

It's a normal part of releasing, I'm not going to forget it.
