### ISSUE TITLE
Lack of examples

### ISSUE THREAD

**Issue by Arth95** [WP-API/OAuth1#69]
Hi!

I started to use wp-api days ago. I felt in love with it, but now comes to learn how to use oAuth1.
I'm frustrated because I cant get through request step.
I'm searching and cant get what should I do.
Only one thing what I get is "No OAuth parameters supplied"
What params should I pass?

**Comment by kosso** [comment]
It's true, there aren't many examples. But you need to understand how to use the OAuth 1.0 spec, which you can find here : https://github.com/WP-API/OAuth1/blob/master/docs/spec.md

Also, it will then depend which language you intend to use this with. eg: PHP, JavaScript, etc. - There are many examples of them. 

In my fork of the OAuth plugin with WP-API, I provided a simple test PHP script to try and authenticate a user : https://github.com/kosso/OAuth1/blob/master/php_test/wp_oauth_test_auth_flow.php

Once you have an 'access_token' for the user of your OAuth client, you then need to 'sign' requests to the server correctly, which the other examples and libraries can help with.

**Comment by rmccue** [comment]
https://github.com/WP-API/example-client is now available; thanks for filing this issue :)
