### ISSUE TITLE
is that possible only user parameter access_token to replace header

### ISSUE THREAD

**Issue by wesleyxiao** [WP-API/OAuth1#71]
currently i am getting oauth1 working well with my mobile app.

and i wondering is that possible send get request like

http://www.example.com/wp-json/users?access_token=W2NILogo2yynwwlzTIlDAb1Q

instead of send all the header 

 headers: {
			
	        'Authorization':
	            'OAuth oauth_consumer_key="aHzRikUJcuLI", ' +
	            'oauth_signature_method="HMAC-SHA1", ' +
	            'oauth_timestamp="1936244848", ' +
	            'oauth_nonce="dsfsda323", ' +
	            'oauth_version="1.0", ' +
	            'oauth_token="W2NILogo2yynwwlzTIlDAb1Q", ' +
	            'oauth_signature="HgunDoJc2WFYdyEOcNigxdl9OTc="'
	    }

**Comment by kosso** [comment]
No. Not for OAuth1.0.  All requested need to be 'signed'. 

To do the style of authentication you are suggesting needs OAuth2.0, where the access_token can be passed like your example, as a query parameter, or as a single request header using `Authorization: Bearer 1234youraccesstoken`  - **BUT**, this should really only be used is your server is running securely through SSL as  **https**://www.example.com/wp-json/users?access_token=W2NILogo2yynwwlzTIlDAb1Q   

Many people do not have the ability to run their server over SSL / https, so this is why we have the OAuth1.0a version. 

This was discussed in a previous issue : https://github.com/WP-API/OAuth1/issues/2#issuecomment-40893119

**Comment by wesleyxiao** [comment]
Thanks kosso
