### ISSUE TITLE
default .htaccess seems to be stripping out the Authorization header

### ISSUE THREAD

**Issue by jeremywho** [WP-API/OAuth1#81]
Spent some time trying to debug why things weren't working for me and found that the .htaccess file was removing the Authorization header.  Although, using a multipart post allowed for the headers to get to OAuth1.  **Maybe this could be documented somewhere?**

Here is the original .htaccess:

```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
```

Here's the modified version that is working for me now:

```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
RewriteBase /
RewriteRule ^index\.php$ - [E=X-HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [E=X-HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]
</IfModule>
# END WordPress
```

**Comment by evgsman** [comment]
Ok dear

**Comment by joehoyle** [comment]
Going to close this in favour of https://github.com/WP-API/OAuth1/issues/161 I think we'll try add it to the WP htaccess block too.

**Comment by tushar4monto** [comment]
Hello

I have added this code 
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
In my .htaccess file but when we update permalinks from admin settings

**Comment by sambenefitz** [comment]
Thanks @jeremywho. The solution worked for me !!

**Comment by crbiz-marx** [comment]
> Spent some time trying to debug why things weren't working for me and found that the .htaccess file was removing the Authorization header. Although, using a multipart post allowed for the headers to get to OAuth1. **Maybe this could be documented somewhere?**
> 
> Here is the original .htaccess:
> 
> ```
> # BEGIN WordPress
> <IfModule mod_rewrite.c>
> RewriteEngine On
> RewriteBase /
> RewriteRule ^index\.php$ - [L]
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule . /index.php [L]
> </IfModule>
> # END WordPress
> ```
> 
> Here's the modified version that is working for me now:
> 
> ```
> # BEGIN WordPress
> <IfModule mod_rewrite.c>
> RewriteEngine On
> RewriteCond %{HTTP:Authorization} ^(.*)
> RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
> RewriteBase /
> RewriteRule ^index\.php$ - [E=X-HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule . /index.php [E=X-HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]
> </IfModule>
> # END WordPress
> ```

this also worked for me. thank you so much.

**Comment by alex-is-therightstuff** [comment]
In order to have my .htaccess be patched automatically I added this wp filter:
```
add_filter('mod_rewrite_rules', function ($rules) {
    return implode(PHP_EOL, array_reduce(array_filter(preg_split('/[\r\n]+/', $rules ?: '')), function ($rules, $line) {
        return array_merge($rules, strpos($line, 'RewriteBase') !== 0 ? [$line] : [
            $line,
            'RewriteCond %{HTTP:Authorization} ^(.*)',
            'RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]',
        ]);
    }, [])) . PHP_EOL;
});
```
It directly modifies the mod rewrite rules as written by Wordpress by adding the two lines
```
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```
right after `RewriteBase /` to result in
```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

I'm no expert for .htaccess files so I'm not 100% sure about where exactly those two lines should be inserted in order to have a clean set of rewrite rules. But this works fine for me, so I thought I'd share this solution.
