### ISSUE TITLE
get_consumer() meta_query not returning the correct consumer application.

### ISSUE THREAD

**Issue by kosso** [WP-API/OAuth1#94]
This was an issue a while ago which seems to still be present. 

If you have more than one client app (consumer) set up, you might find some apps getting signature mismatches. 

After spending some time debugging the Authorization signature and headers being sent by a test client, and also looking deeply at the server signature generation, I discovered that the signature mismatch was due to `get_consumer()` (in class-wp-json-authentication.php) returning the wrong consumer. 

The current master has this query : 

~~~
$query = new WP_Query();
$consumers = $query->query( array(
	'post_type' => 'json_consumer',
	'post_status' => 'any',
	'meta_query' => array(
		array(
			'meta_key' => 'key',
			'meta_value' => $key,
		),
		array(
			'meta_key' => 'type',
			'meta_value' => $this->type,
		),
	),
) );
~~~

But this is returning an array of all consumers/registered applications. Not the one based on its key meta_value. 

I can't seem to form the correct `meta_query` to give back the consumer I expect. 

So, changing the query to this has fixed is for me : 

~~~

$consumers = $query->query( 
	array(
		'post_type' => 'json_consumer',
		'post_status' => 'any',
		'meta_key' => 'key',
		'meta_value' => $key
	)
);
~~~

Which returns the correct consumer, and thus, the correct key to use when creating the signature to compare. 

------

WP : beta nightlies 4.4-beta4-35724
WP-API/WP-API - WP-API-2.0-beta7
WP-API/OAuth1 - master as of today

**Comment by kosso** [comment]
Update to this: I figured out how the `meta_query` should be properly constructed : 

~~~
$consumers = $query->query( array(
    'post_type' => 'json_consumer',
    'post_status' => 'any',
    'meta_query' => array(
        array(
            'key' => 'key',
            'value' => $key,
        ),
        array(
            'key' => 'type',
            'value' => $this->type,
        ),
    ),
));
~~~

Replace `meta_key` and `meta_value` with `key` and `value` in the `meta_query` array.

**Comment by rmccue** [comment]
Hmm, thanks for this, I'll take a look!
